# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322a1c579b1d962e3375d80c64d9e88de875afb3f110f41158fa7180590bf150474f261c5e8e006bfecd9769e0c0d8606e8cbe9d11df4944eeb5010e54fad62f

test:
  secret_key_base: a1a7b6d6d49a0612db517a383a12e344d9938c0acd3a9a0fbc32f2ffb8c535aca47fcfc89d66ffa25169a765b83cbf1ad65d7243ad8186b71272dbdca3663da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
